[project]
    dependencies    = ["jinja2"]
    description     = "Awesome Python CLI tools"
    name            = "awesome-uvx"
    readme          = "README.md"
    requires-python = ">=3.12"
    version         = "0.1.0"
