name: Test Packages

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'pyproject.toml'
      - '.github/scripts/**'
      - '.github/scripts/placeholders/*.json'
  pull_request:
    branches:
      - main
    paths:
      - 'README.md'
      - 'pyproject.toml'
      - '.github/scripts/**'
      - '.github/scripts/placeholders/*.json'

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Make check script executable
        if: runner.os != 'Windows'
        run: chmod +x .github/scripts/checks.py

      - name: Run validation checks
        id: validation
        run: uv run .github/scripts/checks.py
        continue-on-error: true

      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: checks.log
          retention-days: 14

      - name: Check validation status
        if: steps.validation.outcome == 'failure'
        run: exit 1
