jobs:
  validate:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - if: runner.os != 'Windows'
        name: Make check script executable
        run: chmod +x .github/scripts/checks.py

      - continue-on-error: true
        id: validation
        name: Run validation checks
        run: uv run .github/scripts/checks.py

      - if: always()
        name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: checks.log
          retention-days: 14

      - if: steps.validation.outcome == 'failure'
        name: Check validation status
        run: exit 1
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.12', '3.13', '3.14']

name: Test Packages
on:
  pull_request:
    branches:
      - main
    paths:
      - 'README.md'
      - 'pyproject.toml'
      - '.github/scripts/**'
      - '.github/scripts/placeholders/*.json'
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'pyproject.toml'
      - '.github/scripts/**'
      - '.github/scripts/placeholders/*.json'

permissions:
  contents: read
  pull-requests: write
